### ISSUE TITLE
Multiple socket rooms

### ISSUE THREAD

**Issue by catalinberta** [michaelmitchell/redux-socket.io-connect#1]
Does this middleware support multiple room  socket connections? I can't seem to find a way to implement it to handle multiple rooms (at the same time) and use it to dispatch only to certain rooms etc, unless I'm missing the essence here.
Any help in this regard is highly appreciated

**Comment by catalinberta** [comment]
Nevermind, missed the dispatchTo method, awesome middleware!

**Comment by micahnz** [comment]
Thank you for your kind words, I hope you find this useful. If you have any suggestions for improvement let me know.

**Comment by catalinberta** [comment]
Just started with socketio, so still coping here.
Right now, within  a handler, I am trying to do socket.join to subscribe users to rooms, somehow I was expecting the context to have a reference to the socketio instance, but I guess that's not the case?
Maybe I need to to do get this socket reference myself outside of the handler, or maybe the context has it and I didn't figure it out?
