### ISSUE TITLE
Handlers don't receive socket connection events

### ISSUE THREAD

**Issue by catalinberta** [michaelmitchell/redux-socket.io-connect#2]
Handlers should also receive connect, reconnect, disconnect socket events as well, no?
I can listen to all events I emit via actions, all works well here, but I would expect to be able to handle socket connection events via handlers as well, unless I'm missing something

**Comment by micahnz** [comment]
Yup the redux middleware emits socket events by default, take a look in the events section of the api docs for createReduxMiddleware

**Comment by micahnz** [comment]
The middeware dispatches the following redux actions that can be used by the handlers
* `@@redux-socket.io-connect/CONNECT` --- dispatched only once on first `connect` event from socket.io.
* `@@redux-socket.io-connect/CONNECT_ERROR` --- dispatched only once on first `connect_error` event from socket.io.
* `@@redux-socket.io-connect/CONNECT_TIMEOUT` --- dispatched only once on first `connect_timeout` event from socket.io.
* `@@redux-socket.io-connect/RECONNECT` --- dispatched on every `reconnect` event  from socket.io.
* `@@redux-socket.io-connect/RECONNECTING` --- dispatched on every `reconnecting` event  from socket.io.
* `@@redux-socket.io-connect/RECONNECT_ERROR` --- dispatched on every `reconnect_error` event  from socket.io.
* `@@redux-socket.io-connect/RECONNECT_FAILED` --- dispatched on every `reconnect_failed` event  from socket.io.
